env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
ignorePatterns:
  - node_modules
  - Library/PackageCache
  - Assets
  - "**/*.d.ts"
plugins:
  - "@typescript-eslint"
rules:
  indent:
    - warn
    - tab
    - SwitchCase: 1
  space-in-parens:
    - warn
    - never
  linebreak-style:
    - off
    - unix
  quotes:
    - warn
    - single
    - avoidEscape: true
      allowTemplateLiterals: true
  camelcase:
    - warn
    - allow:
        - UI_
        - m_
        - Prefab_
        - Scene_
  consistent-return:
    - error
  no-empty: warn
  no-debugger: warn
  no-constant-condition: off
  prefer-rest-params: warn
  prefer-const: warn
  no-useless-escape: off
  no-async-promise-executor: off
  no-ex-assign: off
  no-mixed-spaces-and-tabs: warn
  semi:
    - warn
    - always
  "@typescript-eslint/no-explicit-any":
    - warn
    - ignoreRestArgs: true
  "@typescript-eslint/no-unused-vars":
    - warn
    - vars: all
      args: none
      ignoreRestSiblings: true
  "@typescript-eslint/ban-types": warn
  "@typescript-eslint/ban-ts-comment": off
  "@typescript-eslint/no-var-requires": off
  "@typescript-eslint/no-empty-function": off
  "@typescript-eslint/no-inferrable-types": off
  "@typescript-eslint/prefer-namespace-keyword": off
  "@typescript-eslint/no-namespace": off
  "@typescript-eslint/no-this-alias": off
